= Go Java Port

This library contains ports of some standard Go packages to Java.

Some of Go features work more or less differently from their siblings in Java.
The goal of this library is to provide the same behavior as Go, avoiding any surprises.

This library can be used to port higher-level libraries from Go to Java.
It is used, for example,
by https://github.com/FIDATA/gradle-packer-plugin[org.fidata.packer] project.

Current version of port is made from Go 1.12.

Licensed under GPL version 2 only with Classpath exception.

== Content

[cols="<,^,",options="header"]
|===
^|Go package
^|Status of port
^|Notes

|`runtime`
| partial
|

|`strings`
| partial
|

|`unicode/utf8`
| partial
| since Java stores strings in UTF-16, this package is ported as `go.unicode.Utf16`

|`os`
| partial
|

|`path/filepath`
| partial
|

|`time`
| partial
|
|===

TODO: list functions & link to javadoc

== Usage

TODO: maven coordinates

All packages are classes are in `go` package. // TODO

Their structure resembles the same of Go.

For example, the following import in Go:

[source,go]
----
import (
 "os"
)
----

becomes the following in Java:

[source,java]
----
import go.Os;
----


''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
Copyright © 2019  Basil Peace

This file is part of go-java-port.

Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.  This file is offered as-is,
without any warranty.
